### ISSUE TITLE
support for @font-face

### ISSUE THREAD

**Issue by martinBadin** [stehefan/postcss-env-replace#1]
Hello, env_replace is not replaced if is in @font-face. Here is the example.

```css
@font-face {
  font-family: 'Lato';
  src: url('env_replace(BASE_URL)/fonts/Lato-Light.eot');
  src: url('env_replace(BASE_URL)/fonts/Lato-Light.eot?#iefix')
      format('embedded-opentype'),
    url('env_replace(BASE_URL)/fonts/Lato-Light.woff2') format('woff2'),
    url('env_replace(BASE_URL)/fonts/Lato-Light.woff') format('woff'),
    url('env_replace(BASE_URL)/fonts/Lato-Light.ttf') format('truetype'),
    url('env_replace(BASE_URL)/fonts/Lato-Light.svg#Lato-Light') format('svg');
  font-weight: 300;
  font-style: normal;
}
```
